improved user experience
Now the script will check if there are already AppDir related to the package you want to create. If it exists, the creation of the AppImage will resume where it left off.
The creation of AppImage can be repeated in case of malfunctions of the previously created AppImage: added a question (Y / N), if Y you will be offered the possibility to export the AppDir again in AppImage, otherwise press N to close the program.

diff --git a/arch-deployer b/arch-deployer
--- a/arch-deployer
+++ b/arch-deployer
@@ -1,6 +1,15 @@
 #!/bin/sh
 
 for APP in $1; do
+   if ls ./$APP/$APP.AppDir; then
+	echo '
+############################################################################
+
+
+ The '$APP'.AppDir already exists!	'
+	sleep 2
+	break
+	else
 	mkdir -p ./$1
 	cd ./$1
 	ARCH=$(uname -m)
@@ -49,17 +58,9 @@ for APP in $1; do
 	wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-$ARCH.AppImage
 	mv ./appimagetool-$ARCH.AppImage ./appimagetool
 	chmod a+x ./appimagetool
-	echo '
-
-
-        The directory '$APP'.AppDir is ready!
-
-
-	'
-done
-function1="'^Exec=.*'"
-function2="'s|%.||g'"
-echo '#!/bin/sh
+	function1="'^Exec=.*'"
+	function2="'s|%.||g'"
+	echo '#!/bin/sh
 HERE="$(dirname "$(readlink -f "${0}")")"
 export UNION_PRELOAD="${HERE}"
 export LD_PRELOAD="${HERE}/libunionpreload.so"
@@ -73,57 +74,63 @@ export GSETTINGS_SCHEMA_DIR="${HERE}"/usr/share/glib-2.0/schemas/:"${GSETTINGS_S
 export QT_PLUGIN_PATH="${HERE}"/usr/lib/qt4/plugins/:"${HERE}"/usr/lib/i386-linux-gnu/qt4/plugins/:"${HERE}"/usr/lib/x86_64-linux-gnu/qt4/plugins/:"${HERE}"/usr/lib32/qt4/plugins/:"${HERE}"/usr/lib64/qt4/plugins/:"${HERE}"/usr/lib/qt5/plugins/:"${HERE}"/usr/lib/i386-linux-gnu/qt5/plugins/:"${HERE}"/usr/lib/x86_64-linux-gnu/qt5/plugins/:"${HERE}"/usr/lib32/qt5/plugins/:"${HERE}"/usr/lib64/qt5/plugins/:"${QT_PLUGIN_PATH}"
 EXEC=$(grep -e '$function1' "${HERE}"/*.desktop | head -n 1 | cut -d "=" -f 2- | sed -e '$function2')
 exec ${EXEC} "$@"' >> AppRun 
-chmod a+x AppRun
+	chmod a+x AppRun
 
-mv ./AppRun ./$APP.AppDir/
-	cp ./$APP.AppDir/usr/share/icons/hicolor/22x22/apps/* ./$APP.AppDir/
-	cp ./$APP.AppDir/usr/share/icons/hicolor/24x24/apps/* ./$APP.AppDir/
-	cp ./$APP.AppDir/usr/share/icons/hicolor/32x32/apps/* ./$APP.AppDir/
-	cp ./$APP.AppDir/usr/share/icons/hicolor/48x48/apps/* ./$APP.AppDir/
-	cp ./$APP.AppDir/usr/share/icons/hicolor/64x64/apps/* ./$APP.AppDir/
-	cp ./$APP.AppDir/usr/share/icons/hicolor/128x128/apps/* ./$APP.AppDir/
-	cp ./$APP.AppDir/usr/share/icons/hicolor/256x256/apps/* ./$APP.AppDir/
-	cp ./$APP.AppDir/usr/share/icons/hicolor/512x512/apps/* ./$APP.AppDir/
-	cp ./$APP.AppDir/usr/share/icons/hicolor/scalable/apps/* ./$APP.AppDir/
-	cp ./$APP.AppDir/usr/share/applications/* ./$APP.AppDir/
-cd ..
-echo '
+	mv ./AppRun ./$APP.AppDir/
+		cp ./$APP.AppDir/usr/share/icons/hicolor/22x22/apps/* ./$APP.AppDir/ 2>/dev/null
+		cp ./$APP.AppDir/usr/share/icons/hicolor/24x24/apps/* ./$APP.AppDir/ 2>/dev/null
+		cp ./$APP.AppDir/usr/share/icons/hicolor/32x32/apps/* ./$APP.AppDir/ 2>/dev/null
+		cp ./$APP.AppDir/usr/share/icons/hicolor/48x48/apps/* ./$APP.AppDir/ 2>/dev/null
+		cp ./$APP.AppDir/usr/share/icons/hicolor/64x64/apps/* ./$APP.AppDir/ 2>/dev/null
+		cp ./$APP.AppDir/usr/share/icons/hicolor/128x128/apps/* ./$APP.AppDir/ 2>/dev/null
+		cp ./$APP.AppDir/usr/share/icons/hicolor/256x256/apps/* ./$APP.AppDir/ 2>/dev/null
+		cp ./$APP.AppDir/usr/share/icons/hicolor/512x512/apps/* ./$APP.AppDir/ 2>/dev/null
+		cp ./$APP.AppDir/usr/share/icons/hicolor/scalable/apps/* ./$APP.AppDir/ 2>/dev/null
+		cp ./$APP.AppDir/usr/share/applications/* ./$APP.AppDir/ 2>/dev/null
+	cd ..
+	echo '
 ############################################################################
 
 
- Opening the '$APP'.AppDir directory, now is possible to check 
+ The '$APP'.AppDir is ready!	'
+	sleep 2
+  fi
+done
+echo '
+ Opening the '$APP'.AppDir directory...
 
- and manually fix any issue before you export it to an AppImage. 
-
- To export '$APP'.AppDir to an AppImage it is sufficient to run:
-
-    "ARCH='$ARCH' ./'$APP'/appimagetool -n ./'$APP'/'$APP'.AppDir" 
-
- YOU CAN ALREADY PERFORM THIS COMMAND IN THE NEXT STEP USING APPIMAGETOOL!
+ You may check it for issues to fix before you export it to an AppImage.
 
 
 ############################################################################
 '
 sleep 2
 xdg-open ./$APP/$APP.AppDir
-
 echo ""
 
-read -p " EXPORTING $APP.AppDir TO AN APPIMAGE, PRESS ANY KEY TO CONTINUE" yn
-case $yn in
-	[Yy]*|[Nn]*|* ) echo ""; ARCH=x86_64 ./$APP/appimagetool -n ./$APP/$APP.AppDir && mv *.AppImage $(xdg-user-dir DESKTOP) 2>/dev/null && echo "" && echo " $APP HAS BEEN EXPORTED ON YOUR DESKTOP!" && echo "" && exit; break;;
-esac
+while true; do
+	read -r -p  " DO YOU WISH TO EXPORT THE $APP.AppDir TO AN APPIMAGE (Y/n)?" response
+	case $response in
+		[Yy]* ) echo ""; ARCH=$(uname -m) ./$APP/appimagetool -n ./$APP/$APP.AppDir 2>/dev/null && 
+			mv *.AppImage $(xdg-user-dir DESKTOP) 2>/dev/null; echo "" &&
+			echo "############################################################################" &&
+			echo "" && echo " $APP HAS BEEN EXPORTED ON YOUR DESKTOP!" && sleep 2 && echo "" && 
+			echo " REPEAT THIS OPERATION IN CASE THE APPIMAGE DOESN'T WORK:" && sleep 2 && echo "" >&2;;
+		[Nn]* ) echo ""; echo " OPERATION ABORTED, EXITING..." && sleep 1 && echo "" && break;;
+		* ) echo ""; echo " PLEASE, ANSWER Y OR N" && echo "" >&2;;
+	esac
+done
 
-echo "
+echo '
 ############################################################################
 
 
-                  THANK YOU FOR USING ARCH-DEPLOYER!
+  THANK YOU FOR USING ARCH-DEPLOYER!
 
-            SITE: https://github.com/ivan-hc/Arch-Deployer
+  PLEASE CONSIDER SUBMITTING YOUR APPLICATION TO "AM"
 
-       SEE ALSO https://github.com/ivan-hc/AM-application-manager
+  SITE: https://github.com/ivan-hc/AM-application-manager
 
 
 ############################################################################
-"
+'
